sources:
  - name: raw
    tables:
      - name: raw_json_data
        description: "This table contains raw JSON data from the source system."
        columns:
          - name: id
            description: "Unique identifier for each record."
          - name: data
            description: "Raw JSON data."
          - name: created_at
            description: "Timestamp when the record was created."
          - name: updated_at
            description: "Timestamp when the record was last updated."